"""DOCX report generator for contract analysis."""

import re
from datetime import datetime
from pathlib import Path
from typing import Optional

try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.style import WD_STYLE_TYPE
    DOCX_AVAILABLE = True
except ImportError:
    DOCX_AVAILABLE = False


def generate_docx_report(
    analysis: str,
    output_path: str,
    title: str = "Contract Analysis Report",
    include_footer: bool = True,
    metadata: Optional[dict] = None
) -> dict:
    """
    Generate a formatted DOCX report from analysis results.
    
    Args:
        analysis: The analysis text (markdown format)
        output_path: Path to save the report
        title: Report title
        include_footer: Whether to include footer with attribution
        metadata: Optional additional metadata to include
        
    Returns:
        dict with status and output path
    """
    if not DOCX_AVAILABLE:
        return {
            "status": "error",
            "message": "python-docx not installed. Run: pip install python-docx"
        }
    
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    doc = Document()
    
    # Add title
    title_para = doc.add_heading(title, 0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add metadata
    meta = doc.add_paragraph()
    meta.add_run(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n").italic = True
    meta.add_run("Tool: Contract Review Skill v0.1.0\n").italic = True
    
    if metadata:
        if "model" in metadata:
            meta.add_run(f"Model: {metadata['model']}\n").italic = True
        if "jurisdiction" in metadata:
            meta.add_run(f"Jurisdiction: {metadata['jurisdiction'].upper()}\n").italic = True
    
    doc.add_paragraph()  # Spacer
    
    # Parse markdown and convert to DOCX
    _parse_markdown_to_docx(doc, analysis)
    
    # Add footer
    if include_footer:
        doc.add_paragraph()
        footer = doc.add_paragraph()
        footer.add_run("This report was generated by Contract Review Skill using Claude AI.").italic = True
        footer.add_run("\nhttps://github.com/claude-office-skills/contract-review-skill").italic = True
    
    doc.save(str(output_path))
    
    return {
        "status": "success",
        "output_path": str(output_path),
        "format": "docx"
    }


def _parse_markdown_to_docx(doc: "Document", markdown_text: str) -> None:
    """
    Parse markdown text and add it to a DOCX document.
    
    Args:
        doc: python-docx Document object
        markdown_text: Markdown formatted text
    """
    lines = markdown_text.split('\n')
    in_code_block = False
    code_buffer = []
    in_table = False
    table_rows = []
    
    for line in lines:
        line = line.rstrip()
        
        # Handle code blocks
        if line.startswith('```'):
            if in_code_block:
                # End of code block
                _add_code_block(doc, code_buffer)
                code_buffer = []
                in_code_block = False
            else:
                # Start of code block
                in_code_block = True
            continue
        
        if in_code_block:
            code_buffer.append(line)
            continue
        
        # Handle tables
        if line.startswith('|') and line.endswith('|'):
            if '---' in line:
                continue  # Skip separator row
            table_rows.append(line)
            in_table = True
            continue
        elif in_table and table_rows:
            _add_table(doc, table_rows)
            table_rows = []
            in_table = False
        
        # Headers
        if line.startswith('#### '):
            doc.add_heading(line[5:], level=4)
        elif line.startswith('### '):
            doc.add_heading(line[4:], level=3)
        elif line.startswith('## '):
            doc.add_heading(line[3:], level=2)
        elif line.startswith('# '):
            doc.add_heading(line[2:], level=1)
        
        # Horizontal rule
        elif line.strip() == '---':
            doc.add_paragraph('─' * 50)
        
        # Bullet points
        elif line.startswith('- ') or line.startswith('* '):
            _add_formatted_paragraph(doc, line[2:], style='List Bullet')
        
        # Checkbox items
        elif line.startswith('- [ ] ') or line.startswith('- [x] '):
            checked = line.startswith('- [x] ')
            text = line[6:]
            prefix = '☑ ' if checked else '☐ '
            _add_formatted_paragraph(doc, prefix + text, style='List Bullet')
        
        # Numbered lists
        elif re.match(r'^\d+\. ', line):
            text = re.sub(r'^\d+\. ', '', line)
            _add_formatted_paragraph(doc, text, style='List Number')
        
        # Regular paragraph with potential formatting
        elif line.strip():
            _add_formatted_paragraph(doc, line)
    
    # Handle remaining table
    if table_rows:
        _add_table(doc, table_rows)


def _add_formatted_paragraph(doc: "Document", text: str, style: Optional[str] = None) -> None:
    """Add a paragraph with inline formatting (bold, italic, code)."""
    if style:
        p = doc.add_paragraph(style=style)
    else:
        p = doc.add_paragraph()
    
    # Split by formatting markers
    # Pattern matches: **bold**, *italic*, `code`
    pattern = r'(\*\*.*?\*\*|\*.*?\*|`.*?`)'
    parts = re.split(pattern, text)
    
    for part in parts:
        if not part:
            continue
        if part.startswith('**') and part.endswith('**'):
            p.add_run(part[2:-2]).bold = True
        elif part.startswith('*') and part.endswith('*') and not part.startswith('**'):
            p.add_run(part[1:-1]).italic = True
        elif part.startswith('`') and part.endswith('`'):
            run = p.add_run(part[1:-1])
            run.font.name = 'Courier New'
            run.font.size = Pt(10)
        else:
            p.add_run(part)


def _add_code_block(doc: "Document", lines: list) -> None:
    """Add a code block with monospace formatting."""
    for line in lines:
        p = doc.add_paragraph()
        run = p.add_run(line)
        run.font.name = 'Courier New'
        run.font.size = Pt(9)
        p.paragraph_format.left_indent = Inches(0.5)


def _add_table(doc: "Document", rows: list) -> None:
    """Add a table from markdown table rows."""
    if not rows:
        return
    
    # Parse header row
    header_cells = [cell.strip() for cell in rows[0].split('|')[1:-1]]
    num_cols = len(header_cells)
    
    # Create table
    table = doc.add_table(rows=len(rows), cols=num_cols)
    table.style = 'Table Grid'
    
    for row_idx, row_text in enumerate(rows):
        cells = [cell.strip() for cell in row_text.split('|')[1:-1]]
        for col_idx, cell_text in enumerate(cells[:num_cols]):
            cell = table.rows[row_idx].cells[col_idx]
            # Make header bold
            if row_idx == 0:
                cell.paragraphs[0].add_run(cell_text).bold = True
            else:
                cell.text = cell_text
    
    doc.add_paragraph()  # Add spacing after table
