"""Markdown report generator for contract analysis."""

from datetime import datetime
from pathlib import Path
from typing import Optional


def generate_markdown_report(
    analysis: str,
    output_path: str,
    title: str = "Contract Analysis Report",
    include_footer: bool = True,
    metadata: Optional[dict] = None
) -> dict:
    """
    Generate a formatted Markdown report from analysis results.
    
    Args:
        analysis: The analysis text (markdown format)
        output_path: Path to save the report
        title: Report title
        include_footer: Whether to include footer with attribution
        metadata: Optional additional metadata to include
        
    Returns:
        dict with status and output path
    """
    output_path = Path(output_path)
    
    # Build metadata section
    meta_lines = [
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "**Tool:** Contract Review Skill v0.1.0"
    ]
    
    if metadata:
        if "model" in metadata:
            meta_lines.append(f"**Model:** {metadata['model']}")
        if "jurisdiction" in metadata:
            meta_lines.append(f"**Jurisdiction:** {metadata['jurisdiction'].upper()}")
        if "tokens" in metadata:
            meta_lines.append(f"**Tokens:** {metadata['tokens']['input']} input, {metadata['tokens']['output']} output")
    
    # Build report
    report_parts = [
        f"# {title}",
        "",
        "\n".join(meta_lines),
        "",
        "---",
        "",
        analysis
    ]
    
    if include_footer:
        report_parts.extend([
            "",
            "---",
            "",
            "*This report was generated by Contract Review Skill using Claude AI.*",
            "*https://github.com/claude-office-skills/contract-review-skill*"
        ])
    
    report_content = "\n".join(report_parts)
    
    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report_content, encoding="utf-8")
    
    return {
        "status": "success",
        "output_path": str(output_path),
        "format": "markdown"
    }


def format_risk_summary(risks: dict) -> str:
    """
    Format a risk summary as a Markdown table.
    
    Args:
        risks: Dict with high/medium/low risk items
        
    Returns:
        Formatted Markdown string
    """
    lines = [
        "## Risk Summary",
        "",
        "| Severity | Count | Key Issues |",
        "|----------|-------|------------|"
    ]
    
    for severity, items in risks.items():
        if items:
            key_issues = ", ".join(item.get("name", "Unknown")[:30] for item in items[:3])
            if len(items) > 3:
                key_issues += f" (+{len(items) - 3} more)"
            lines.append(f"| {severity.title()} | {len(items)} | {key_issues} |")
    
    return "\n".join(lines)


def format_key_terms_table(terms: dict) -> str:
    """
    Format key terms as a Markdown table.
    
    Args:
        terms: Dict with extracted key terms
        
    Returns:
        Formatted Markdown string
    """
    lines = [
        "## Key Terms",
        "",
        "| Term | Value | Notes |",
        "|------|-------|-------|"
    ]
    
    # Standard terms to extract
    term_mappings = [
        ("Contract Type", terms.get("contract_type")),
        ("Effective Date", terms.get("dates", {}).get("effective_date")),
        ("End Date", terms.get("dates", {}).get("end_date")),
        ("Total Value", terms.get("financial_terms", {}).get("total_value")),
        ("Payment Terms", terms.get("financial_terms", {}).get("payment_terms")),
        ("Governing Law", terms.get("dispute_resolution", {}).get("governing_law")),
    ]
    
    for term_name, value in term_mappings:
        if value:
            lines.append(f"| {term_name} | {value} | - |")
    
    return "\n".join(lines)
